travis:
  secure:
    BINSTAR_TOKEN: SrXcd3peX+XBCynPbR/wihp2zhtqEiR0KDXPD72NIjibvAKDUHaKwoUe1MOqkwVOd3iowjNTnK70auuLnpDvUxcH6ciwf/AGDU0iuzykA+CRdTNHKrKgGTZI6lkJpGRfiMKKN31OACpj2QdpV+IZ984ByEenNWtHdbRHjt2ezgGW2PDwbXdmUXaE+z/9gtUHyguNjkB950Vs85roP1JUOHA7ewt9Cqaw+Mn7chz/6ljoZce6dLVGEZGdCrlD4ohKRy34lOb3sXns+H1zECeLlX3of+vXuGwPIRV1+oVyc4qz91bsMo8wyBinPURHCCfi503klxolOrQY0aPHHy1CRb+ddEygpaInr0DwVnWKAUTE+JzqQJt08zrtzYmbCAsnlFiMXP/i8gda6VG0Oj+P/aUeLxmUcI38OWgOcF6shiguGfsJi2fs4UVWVccomImVT7wxUNcTkOBQ27m0ft81QPwbE7VVKE+ULPKuXKI1ZuK5hjtsmGWcr17usmfns3DS8G3ohfVlhveV0a9Ctj6bVJ9//HBYzYdMmfBgbbqOGdcoDhPZAofwsEYWUH/qGicQumT6uV+rR+eALNvL5sSXpv1+Jp4whJmWt4GyCdxAjXjiIOo0yxWfVbTyzS0FgLADIqHJh2D05QkFCiUaBGQ7GoP4sxl1C4TFR7PMQkjwkmU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
