travis:
  secure:
    BINSTAR_TOKEN: KoakvOJjm30PbQiYDfvoQH3NEwBKEeOdaPFHtYuTEyYttsWQ/GlJW2WegTe38L5DO9GPRVsPKD03LfTO7jHi4U2+2W4uZfBS78z1r4wNwNUes7URV+lPLKV30PN8PQxbNo5gITIQfndVCwBkzgpqUpUVafTWBocWoipxabieZi8EzUwlpueeBz1AKBKjhBs/vttGio6wOwG+zVx0fqSdNcjiaOZWSecKStmcKsOQaOVv8zCDbaNQVDBxTW/WvInisYo+uWNeF3wuipLNxGpLu1cKX8zKv7qd8lpPDSctSrlHMfdzQX/umyUNBvFKJ+mkEyKyXcjOvXEHmHpkfculcEXKgdQ87jAQP31recSK9TZSTpv1IA8+Gx2tCUTtzsdYeCB5ZFo0WChZOMn1Ew6K+Cy825JOCcY8xW4djkgnX/F3IJJ+no4cGVV2uoErY1qeZ/lG3cIUQiCzynbt3rlgwiMVfpgk4f7+z+zrp/LwnQWg4TTnlhtRG72caq5JfgogEfGk2cfesT7LHP3AhUZHMXfYurytcizpjcODwM/P+cbU/nEU7dcORPJws3/9yfC/yG8JvGQ/EyDaBqEtlCFYPXSH7KwMhRvTfAk6d852kELMRnA2GW1/YKti4De+nVldQuzOa9DL2oLQJ7tLFj/QzLo3Bn63b/oC32CU/BeBJfw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
